apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ak3hay/preso-web
    newTag: "ab3e6b6f"
  - name: ak3hay/preso-python-agent
    newTag: "ab3e6b6f"
  - name: ak3hay/preso-node-worker
    newTag: "ab3e6b6f"
  - name: ak3hay/preso-pptx-agent
    newTag: "ab3e6b6f"

patchesStrategicMerge:
  - replicas-patch.yaml
