apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ak3hay/preso-web
    newTag: "2897c4b5"
  - name: ak3hay/preso-python-agent
    newTag: "2897c4b5"
  - name: ak3hay/preso-node-worker
    newTag: "2897c4b5"
  - name: ak3hay/preso-mcp-server
    newTag: "2897c4b5"
  - name: ak3hay/preso-pptx-agent
    newTag: "2897c4b5"

patchesStrategicMerge:
  - replicas-patch.yaml
