apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ak3hay/preso-web
    newTag: 192ada3e
  - name: ak3hay/preso-python-agent
    newTag: 192ada3e
  - name: ak3hay/preso-node-worker
    newTag: 192ada3e
  - name: ak3hay/preso-pptx-agent
    newTag: 192ada3e
