apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ak3hay/preso-web
    newTag: "e3c2d093"
  - name: ak3hay/preso-python-agent
    newTag: "e3c2d093"
  - name: ak3hay/preso-node-worker
    newTag: "e3c2d093"
  - name: ak3hay/preso-mcp-server
    newTag: "e3c2d093"
  - name: ak3hay/preso-pptx-agent
    newTag: "e3c2d093"
